template: true
valuesFilePath: ./values-docker.yml

resources:
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}
      files:
        include: {{ .Values.gitRepo.files.include }}
      # branches:
      #   include: {{ .Values.gitRepo.branch }}

  - name: "{{ .Values.pipelines.name }}_image"
    type: Image
    configuration:
      registry: {{ .Values.artifactory }}
      sourceRepository: {{ .Values.artifactoryRepo.deployer.name }}
      imageName: "{{ .Values.docker.image.registry }}/{{ .Values.artifactoryRepo.deployer.name }}/{{ .Values.docker.image.name }}"
      imageTag: ${run_number}
      
  - name: {{ .Values.pipelines.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

  # - name: "{{ .Values.pipelines.name }}_promoted"
  #   type: BuildInfo
  #   configuration:
  #     sourceArtifactory: {{ .Values.artifactory }}      

pipelines:
  - name: {{ .Values.pipelines.name }}
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: {{ .Values.pipelines.name }}
          dockerFileLocation: {{ .Values.docker.file.location }}
          dockerFileName: {{ .Values.docker.file.name }}
          dockerImageName: "{{ .Values.docker.image.registry }}/{{ .Values.artifactoryRepo.deployer.name }}/{{ .Values.docker.image.name }}"
          dockerImageTag: ${run_number}

          integrations:
            - name: {{ .Values.artifactory }}

          inputResources:
            - name: {{ .Values.gitRepo.name }}
            - name: {{ .Values.pipelines.app.name }}

        execution:
          onStart:
            - jfrog rt dl demo-go/jfrog_demo ${res_{{ .Values.gitRepo.name }}_resourcePath}/{{ .Values.application.name }}
            - chmod +x ${res_{{ .Values.gitRepo.name }}_resourcePath}/{{ .Values.application.name }}
            # - echo "[TM] manually login to artifactory"
            # - echo ${int_{{ .Values.artifactory }}_apikey} | docker login --username {{ .Values.artifactoryRepo.username }} --password-stdin ${int_{{ .Values.artifactory }}_url}

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: {{ .Values.pipelines.name }}
          targetRepository: {{ .Values.artifactoryRepo.deployer.name }}
          forceXrayScan: true
          autoPublishBuildInfo: true

          integrations:
            - name: {{ .Values.artifactory }}

          inputSteps:
            - name: docker_build
          outputResources:
            - name: "{{ .Values.pipelines.name }}_image"
            - name: {{ .Values.pipelines.name }}

      # - name: promote_build
      #   type: PromoteBuild
      #   configuration:
      #     targetRepository: {{ .Values.artifactoryRepo.promote.name }}
      #     integrations:
      #       - name: {{ .Values.artifactory }}
      #     inputResources:
      #       - name: {{ .Values.pipelines.name }}
      #     outputResources:
      #       - name: "{{ .Values.pipelines.name }}_promoted"
