template: true
valuesFilePath: ./values-app.yml

resources:
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}
      files:
        include: {{ .Values.gitRepo.files.include }}
      # branches:
      #   include: main

  - name: {{ .Values.pipelines.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}


pipelines:
  - name: {{ .Values.pipelines.name }}
    steps:
      - name: go_build
        type: GoBuild
        configuration:
          environmentVariables:
            GO111MODULE: on
            CGO_ENABLED: 0
            GOOS: linux
            GOARCH: amd64
          # sourceLocation: .
          # outputLocation: .
          outputFile: {{ .Values.application.name }}
          resolverRepo: {{ .Values.artifactoryRepo.resolver.name }}

          integrations:
            - name: {{ .Values.artifactory }}

          inputResources:
            - name: {{ .Values.gitRepo.name }}

      - name: go_publish_binary
        type: GoPublishBinary
        configuration:
          forceXrayScan: true
          autoPublishBuildInfo: true
          targetRepository: {{ .Values.artifactoryRepo.deployer.name }}

          integrations:
            - name: {{ .Values.artifactory }}

          inputSteps:
            - name: go_build
          outputResources:
            - name: {{ .Values.pipelines.name }}
          