artifactory: artifactory
pipelines:
  name: jfrog_demo_core_app
gitRepo:
  name: jfrog_demo_core_app_gitrepo
  provider: github
  path: tsuyo/jfrog-demo-core
  files:
    include: main.go|go.mod|go.sum
artifactoryRepo:
  resolver:
    name: demo-go
  deployer:
    name: demo-go
application:
  name: jfrog_demo_core
