artifactory: artifactory
pipelines:
  name: jfrog_demo_build
gitRepo:
  name: github_jfrog_demo
  provider: github
  path: tsuyo/jfrog-demo
  files:
    include: main.go|go.mod|go.sum
artifactoryRepo:
  resolver:
    name: demo-go
  deployer:
    name: demo-go
application:
  name: jfrog_demo    
