artifactory: artifactory
pipelines:
  name: jfrog_demo_core_docker
  app:
    name: jfrog_demo_core_app
gitRepo:
  name: jfrog_demo_core_docker_gitrepo
  provider: github
  path: tsuyo/jfrog-demo
  files:
    include: Dockerfile
  # branch: main
artifactoryRepo:
  resolver:
    name: demo-docker
  deployer:
    name: demo-docker
  # promote:
  #   name: demo-docker-prod
  # username: admin
application:
  name: jfrog_demo_core
docker:
  image:
    registry: platform.dev.gcp.tsuyo.org
    name: jfrog-demo-core
  file:
    location: .
    name: Dockerfile
