artifactory: artifactory
pipelines:
  name: jfrog_demo_docker
  build:
    name: jfrog_demo_build
gitRepo:
  name: github_jfrog_demo_docker
  provider: github
  path: tsuyo/jfrog-demo
  files:
    include: Dockerfile
  # branch: main
artifactoryRepo:
  resolver:
    name: demo-docker
  deployer:
    name: demo-docker
  # promote:
  #   name: demo-docker-prod-local
  # username: admin
docker:
  image:
    registry: platform.dev.gcp.tsuyo.org
    name: jfrog-demo
    # tag: latest
  file:
    location: .
    name: Dockerfile